name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Uses a pre-built compiler container so it doesn't crash on NDK downloads
      - name: Buildozer Action
        uses: ArtemNikitin/buildozer-action@v1
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Upload Finished APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: titan-flipper-apk
          path: bin/*.apk
